# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tema',
            options={'ordering': ['modulo__nombre', 'numero']},
        ),
        migrations.AddField(
            model_name='tema',
            name='adicional',
            field=models.CharField(default='', max_length=4096),
            preserve_default=False,
        ),
    ]
