# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('codigo_junta', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='apellidos',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumno',
            name='dni',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
    ]
