# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 09:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumnos', '0002_auto_20170620_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoCursaModulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repite_modulo', models.BooleanField()),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Alumno')),
            ],
        ),
        migrations.AddField(
            model_name='modulo',
            name='nombre',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumnocursamodulo',
            name='modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alumnos.Modulo'),
        ),
    ]
